import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Klam',
  description: 'Terms governing your use of the Klam mobile application.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-cream-50 text-ink-900">
      <header className="border-b border-cream-200 bg-cream-50 px-4 sm:px-6 py-4">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <Link href="/" className="font-display text-title text-ink-900 hover:opacity-80 transition-opacity">
            Klam
          </Link>
          <span className="text-small text-ink-500">Terms of Service</span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 sm:px-6 py-10 sm:py-16">
        <h1 className="font-display text-2xl sm:text-[2rem] leading-tight text-ink-900 mb-2">
          Terms of Service
        </h1>
        <p className="text-small text-ink-500 mb-8">
          Effective date: July 7, 2026 &nbsp;·&nbsp; Last updated: July 7, 2026
        </p>

        <div className="space-y-10 text-body text-ink-600 leading-relaxed">
          <p>
            These Terms of Service ("Terms") govern your use of the Klam mobile application (the "App"), operated by{' '}
            <strong className="text-ink-900">Mohamed Adnane Al Khiati</strong> ("Klam," "we," "us," or "our"). By creating an account or using the App, you agree to these Terms. If you don't agree, don't use the App. Our{' '}
            <Link href="/privacy" className="text-ink-900 underline underline-offset-2 hover:opacity-70 transition-opacity">
              Privacy Policy
            </Link>{' '}
            explains how we handle your data and is incorporated into these Terms by reference.
          </p>

          <Section title="1. Eligibility">
            <p>
              You must be at least <strong className="text-ink-900">18 years old</strong> to use Klam. By using the App, you represent that you meet this requirement and that all information you provide is accurate.
            </p>
          </Section>

          <Section title="2. Your Account">
            <ul className="list-disc space-y-2 pl-5">
              <li>
                You create an account by signing in with <strong className="text-ink-900">Google</strong> or <strong className="text-ink-900">Apple</strong>. Klam does not have its own password system — your account security depends on the security of your Google/Apple account.
              </li>
              <li>
                If you sign in with a different provider using the same email address as an existing Klam account, we'll link them into a single account.
              </li>
              <li>
                You're responsible for all activity under your account. Notify us immediately if you suspect unauthorized access.
              </li>
              <li>
                You may delete your account at any time from within the App. See our Privacy Policy for what happens to your data when you do.
              </li>
            </ul>
          </Section>

          <Section title="3. The Service">
            <p className="mb-4">
              Klam lets you record yourself practicing public speaking exercises, receive an automatically generated transcript, and receive <strong className="text-ink-900">AI-generated feedback</strong> — scores, coaching suggestions, word-level notes, and example rewrites — along with gamification features (XP, streaks, badges) to track your progress.
            </p>
            <p>
              <strong className="text-ink-900">Klam is a self-practice tool, not professional advice.</strong> The feedback and scores generated by the App are produced automatically by third-party AI models and are provided for informational and practice purposes only. They are <strong className="text-ink-900">not</strong> a substitute for professional speech therapy, coaching, education, career, medical, or clinical advice, and may contain errors, omissions, or inaccuracies. Use your own judgment, and consult a qualified professional for anything that matters.
            </p>
          </Section>

          <Section title="4. Your Content">
            <p className="mb-4">
              "Your Content" means the audio recordings, transcripts, self-assessment ratings, and notes you create using the App.
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                <strong className="text-ink-900">You own Your Content.</strong> We don't claim ownership over what you record or write.
              </li>
              <li>
                <strong className="text-ink-900">You grant us a license</strong> to store, process, transmit, and reproduce Your Content solely as needed to operate and improve the App — including sending it to the third-party transcription and AI-feedback providers described in our Privacy Policy.
              </li>
              <li>
                <strong className="text-ink-900">You're responsible for Your Content.</strong> Don't record or submit anything illegal, infringing on someone else's rights, hateful, or harmful. We may remove Content or suspend accounts that violate this.
              </li>
            </ul>
          </Section>

          <Section title="5. Acceptable Use">
            <p className="mb-4">You agree not to:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Use the App for any unlawful purpose or in violation of these Terms;</li>
              <li>Attempt to access another user's account or data;</li>
              <li>Reverse-engineer, decompile, or attempt to extract the App's source code, models, or underlying prompts;</li>
              <li>Interfere with or disrupt the App's infrastructure or attempt to bypass rate limits or authentication;</li>
              <li>Use automated means (bots, scrapers) to access the App outside of the official client.</li>
            </ul>
            <p className="mt-4">We may suspend or terminate accounts that violate this section.</p>
          </Section>

          <Section title="6. Third-Party Services">
            <p>
              The App relies on third-party services (including Google, Apple, AWS, DigitalOcean, AssemblyAI, Deepgram, DeepSeek, and Expo) to function. We are not responsible for the availability, performance, or acts and omissions of these third parties, though we choose and configure them carefully. Details on what data each receives are in our{' '}
              <Link href="/privacy" className="text-ink-900 underline underline-offset-2 hover:opacity-70 transition-opacity">
                Privacy Policy
              </Link>.
            </p>
          </Section>

          <Section title="7. Intellectual Property">
            <p>
              The App itself — its design, code, exercise catalogs, badge/level systems, and branding — is owned by Klam and protected by intellectual property laws. These Terms don't grant you any rights to our intellectual property beyond the limited right to use the App as intended.
            </p>
          </Section>

          <Section title="8. Limited License">
            <p className="mb-4">
              Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to use the App for your personal, non-commercial use. We may modify, suspend, or discontinue features at any time.
            </p>
            <p className="mb-4">
              We are not responsible for delays or failures caused by events outside our reasonable control, including internet outages, cloud-provider failures, natural disasters, governmental actions, or cyberattacks.
            </p>
            <p className="mb-4">
              These Terms, together with the Privacy Policy, constitute the entire agreement between you and Klam regarding the App.
            </p>
            <p className="mb-4">
              If any provision of these Terms is found unenforceable, the remaining provisions remain in effect.
            </p>
            <p>
              Our failure to enforce any provision of these Terms does not constitute a waiver of that provision.
            </p>
          </Section>

          <Section title="9. No Payment at This Time">
            <p>
              Klam does not currently charge for access or offer in-app purchases. If that changes in the future, we'll update these Terms to include applicable billing, subscription, and refund terms before introducing any paid features.
            </p>
          </Section>

          <Section title="10. Disclaimers">
            <p className="uppercase text-small tracking-wide text-ink-700">
              The App is provided "as is" and "as available," without warranties of any kind, either express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not guarantee that the App will be uninterrupted, error-free, or that AI-generated feedback will be accurate.
            </p>
          </Section>

          <Section title="11. Limitation of Liability">
            <p className="uppercase text-small tracking-wide text-ink-700 mb-4">
              To the maximum extent permitted by law, Klam and its operator shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data, arising from your use of the App. Our total liability for any claim arising from these Terms or the App shall not exceed the amount you paid us in the 12 months preceding the claim (which, as the App is currently free, may be zero).
            </p>
            <p>
              Some jurisdictions don't allow the exclusion or limitation of certain damages, so some of the above limitations may not apply to you.
            </p>
          </Section>

          <Section title="12. Termination">
            <p>
              You may stop using the App and delete your account at any time. We may suspend or terminate your access if you violate these Terms, or discontinue the App at our discretion, with reasonable notice where practical.
            </p>
          </Section>

          <Section title="13. Changes to These Terms">
            <p>
              We may update these Terms from time to time. If we make material changes, we'll notify you through the App before they take effect. Continued use of the App after changes take effect means you accept the updated Terms.
            </p>
          </Section>

          <Section title="14. Governing Law">
            <p>
              These Terms are governed by the laws of <strong className="text-ink-900">Morocco</strong>, without regard to conflict-of-law principles. Any disputes will be resolved in the courts of that jurisdiction, unless otherwise required by applicable local consumer-protection law.
            </p>
          </Section>

          <Section title="15. Contact Us">
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:adnanealk@gmail.com" className="text-ink-900 underline underline-offset-2 hover:opacity-70 transition-opacity">
                adnanealk@gmail.com
              </a>.
            </p>
          </Section>
        </div>

        <div className="mt-12 border-t border-cream-200 pt-8 text-small text-ink-500">
          <Link href="/" className="hover:text-ink-900 transition-colors">
            ← Back to Klam
          </Link>
        </div>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-large text-ink-900 mb-3">{title}</h2>
      {children}
    </section>
  )
}
